name: Azure Infrastructure Provisioning

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  provision:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure-actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

       
    - name: Terraform Apply
      run: terraform apply --auto-approve
        
  destroy:
    runs-on: ubuntu-latest
    needs: provision
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure-actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Terraform Destroy
      run: terraform destroy --auto-approve